version: '3'

services:
  opentasksDB:
    image: postgres:15.3
    container_name: opentasks
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - opentasksvol:/var/lib/postgresql/data

volumes:
  opentasksvol:


networks:
  nextwork:
    driver: bridge
